name: Build Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt-get install meson
          meson setup build
          meson compile -C build
